Vagrant.configure("2") do |config|
    N = 3
    (1..N).each do |machine_id|
        config.vm.define "machine#{machine_id}" do |machine|
            machine.vm.hostname = "machine#{machine_id}"
            machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"
            machine.vm.box = "jessie"
            machine.vm.box_url = "https://github.com/kraksoft/vagrant-box-debian/releases/download/8.1.0/debian-8.1.0-amd64.box"
            machine.vm.synced_folder ".", "/vagrant", disabled: true

            # Only execute once the Ansible provisioner,
            # when all the machines are up and ready.
            if machine_id == 3
                machine.vm.provision :ansible do |ansible|
                    # Disable default limit to connect to all the machines
                    ansible.limit = "all"
                    ansible.playbook = "playbook.yml"
                end
            end
        end
    end
end
